name: PHP Linting
on: pull_request
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: "laravel-pint"
          uses: codenia-devops/laravel-pint-action@203c2fea1102e51381b31e153de5ea7296626c72
          with:
            preset: laravel
            verboseMode: true
            testMode: true
            configPath: "vendor/my-company/coding-style/pint.json"
            pintVersion: 1.2.1
